name: $(majorMinorVersion).$(semanticVersion)-PR # $(rev:r) 

trigger: none
 
pr:
- master


variables:
- template: cicd/variables.yml

stages:
  - stage: 'BuildAndCompile'
    displayName: 'Build'
    jobs:
      - job: 
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: cicd/linux-build.yml
            parameters:
              doPublish: false
      - job: 
        pool:
          vmImage: 'windows-latest'
        steps:
          - template: cicd/win-build.yml
            parameters:
              doPublish: false