name: $(majorMinorVersion).$(semanticVersion)-RC # $(rev:r) 

trigger:
  branches:
    include:
    - master

pr: none

variables:
- template: cicd/variables.yml

stages:
  - stage: 'BuildAndCompile'
    displayName: 'Build'
    jobs:
      - job: 
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: cicd/linux-build.yml
            parameters:
              doPublish: true
              tag: '$(majorMinorVersion).$(semanticVersion)-RC'
      - job: 
        pool:
          vmImage: 'windows-latest'
        steps:
          - template: cicd/win-build.yml
            parameters:
              doPublish: true
              tag: '$(majorMinorVersion).$(semanticVersion)-RC'