name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) 

trigger:
  tags:
   include:
    - '*'

pr: none


variables:
- template: cicd/variables.yml

stages:
  - stage: 'BuildAndCompile'
    displayName: 'Build'
    jobs:
      - job: 
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: cicd/linux-build.yml
            parameters:
              doPublish: true
              tag: '$(tag)'
      - job: 
        pool:
          vmImage: 'windows-latest'
        steps:
          - template: cicd/win-build.yml
            parameters:
              doPublish: true
              tag: '$(tag)'

stages:
  - stage: 'BuildAndPublish'
    displayName: 'Build and Publish'
    jobs:
      - job: 
        steps:
          - template: cicd/steps.yml
            parameters:
              doPublish: true
              tag: '$(tag)'